apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentry-relay
  namespace: monitoring
  labels:
    app: sentry-relay
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentry-relay
  template:
    metadata:
      labels:
        app: sentry-relay
    spec:
      containers:
      - name: sentry-relay
        image: getsentry/relay:22.12.0
        ports:
        - containerPort: 3000
        env:
        - name: RELAY_MODE
          value: "managed"
        - name: RELAY_UPSTREAM
          value: "https://sentry.io"
        - name: RELAY_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: sentry-secrets
              key: relay-secret-key
        - name: RELAY_PUBLIC_KEY
          valueFrom:
            secretKeyRef:
              name: sentry-secrets
              key: relay-public-key
        - name: RELAY_ID
          valueFrom:
            secretKeyRef:
              name: sentry-secrets
              key: relay-id
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: sentry-relay
  namespace: monitoring
  labels:
    app: sentry-relay
spec:
  selector:
    app: sentry-relay
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
  type: ClusterIP 