import { useQuery } from '@tanstack/react-query';
import {
  Apple,
  Droplets,
  Dumbbell,
  Footprints,
  Info,
  Moon,
  Sparkles,
  type LucideIcon,
} from 'lucide-react';
import type { InsightType } from '@shared/schema';
import { ErrorState } from '@/components/common/States';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent } from '@/components/ui/card';
import { Skeleton } from '@/components/ui/skeleton';
import { api } from '@/lib/api';

const META: Record<InsightType, { icon: LucideIcon; label: string }> = {
  activity: { icon: Footprints, label: 'Activity' },
  sleep: { icon: Moon, label: 'Sleep' },
  hydration: { icon: Droplets, label: 'Hydration' },
  workout: { icon: Dumbbell, label: 'Training' },
  nutrition: { icon: Apple, label: 'Nutrition' },
};

export default function Insights() {
  const { data, isLoading, error, refetch } = useQuery({
    queryKey: ['insights'],
    queryFn: () => api.insights(),
  });

  return (
    <div className="space-y-6">
      <div>
        <h1 className="font-display text-2xl font-bold">Insights</h1>
        <p className="mt-0.5 text-sm text-text-muted">
          Generated from your last 14 days of logged activity.
        </p>
      </div>

      {/*
        Stated plainly and permanently: this is a rules engine, not a language
        model. Claiming otherwise would be the easiest lie in the project.
      */}
      <Card className="border-info/30 bg-info/5">
        <CardContent className="flex gap-3 p-4">
          <Info className="mt-0.5 size-4 shrink-0 text-info" aria-hidden="true" />
          <p className="text-sm text-text-muted">
            <span className="font-medium text-text">Rule-based insights.</span> These are computed
            from thresholds and trends in your own numbers — not generated by a language model.
            Every card shows the data it was derived from.
          </p>
        </CardContent>
      </Card>

      {error ? (
        <ErrorState message="We could not generate your insights." onRetry={() => void refetch()} />
      ) : isLoading ? (
        <div className="space-y-4">
          {Array.from({ length: 3 }, (_, i) => (
            <Skeleton key={i} className="h-36" />
          ))}
        </div>
      ) : (
        <ul className="space-y-4">
          {(data?.insights ?? []).map((insight) => {
            const meta = META[insight.type];
            const Icon = meta.icon;
            return (
              <li key={insight.id}>
                <Card>
                  <CardContent className="flex gap-4 p-5">
                    <span className="flex size-10 shrink-0 items-center justify-center rounded-full bg-surface-raised">
                      <Icon className="size-4 text-text-muted" aria-hidden="true" />
                    </span>
                    <div className="min-w-0 flex-1">
                      <div className="flex flex-wrap items-center gap-2">
                        <h2 className="font-display text-base font-semibold">{insight.title}</h2>
                        <Badge>{meta.label}</Badge>
                      </div>
                      <p className="mt-2 text-sm leading-relaxed text-text-muted">{insight.body}</p>
                      <p className="mt-3 flex items-center gap-1.5 text-2xs uppercase text-text-subtle">
                        <Sparkles className="size-3" aria-hidden="true" />
                        Based on {insight.basis}
                      </p>
                    </div>
                  </CardContent>
                </Card>
              </li>
            );
          })}
        </ul>
      )}
    </div>
  );
}
