apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthhubpro-api
  namespace: production
  labels:
    app: healthhubpro
    component: api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthhubpro
      component: api
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: healthhubpro
        component: api
    spec:
      containers:
      - name: api
        image: ${ECR_REPOSITORY_URI}:${GITHUB_SHA}
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: healthhubpro-secrets
              key: database-url
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: healthhubpro-secrets
              key: redis-url
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: healthhubpro-secrets
              key: session-secret
        - name: OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: healthhubpro-secrets
              key: openai-api-key
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "500m"
            memory: "512Mi"
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 15
          periodSeconds: 20
      imagePullSecrets:
      - name: ecr-secret 